"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var confirm_1 = require("./confirm");
exports.confirm = confirm_1.default;
var tips_1 = require("./tips");
exports.tips = tips_1.default;
var checkbox_1 = require("./checkbox");
exports.Checkbox = checkbox_1.default;
var slide_1 = require("./slide");
exports.Slide = slide_1.default;
